[package]
name = "httpie"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1" # 错误处理
clap = "3.0.0-beta.4" # 命令行解析
colored = "2" # 命令终端多彩显示
syntect = "4.6.0" # 语法高亮
reqwest = { version = "0.11", features = ["json"] }